services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ${COMPOSER_HOME}:/.composer:consistent
    environment:
      DATABASE_URL: mysql://messenger:messenger@mysql:3306/messenger_test
      MESSENGER_AMQP_DSN: amqp://guest:guest@rabbitmq:5672/%2f
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: messenger_test
      MYSQL_USER: messenger
      MYSQL_PASSWORD: messenger
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mysql_data:
  rabbitmq_data:

