<?php

declare(strict_types=1);

namespace Freyr\MessageBroker\Tests\Unit\Fixtures;

use Carbon\CarbonImmutable;
use Freyr\Identity\Id;
use Freyr\MessageBroker\Outbox\EventBridge\OutboxMessage;
use Freyr\MessageBroker\Outbox\MessageName;

/**
 * Test message for unit testing outbox serialization.
 *
 * Simple message with basic business properties.
 * No messageId property - it's auto-generated by OutboxToAmqpBridge.
 */
#[MessageName('test.message.sent')]
final readonly class TestMessage implements OutboxMessage
{
    public function __construct(
        public Id $id,
        public string $name,
        public CarbonImmutable $timestamp,
    ) {}
}
