# Example configuration for typed inbox message processing

# 1. Define message type mappings
parameters:
    inbox.message_types:
        # Map message_name => PHP class
        'order.placed': 'App\Message\OrderPlaced'
        'order.cancelled': 'App\Message\OrderCancelled'
        'user.registered': 'App\Message\UserRegistered'
        'user.updated': 'App\Message\UserUpdated'

# 2. Configure services
services:
    # Typed inbox serializer
    Freyr\MessageBroker\Inbox\Serializer\TypedInboxSerializer:
        arguments:
            $messageTypes: '%inbox.message_types%'

    # Inbox transport factory (required for inbox://)
    Freyr\MessageBroker\Inbox\Transport\DoctrineInboxTransportFactory:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
        tags: ['messenger.transport_factory']

# 3. Configure messenger transports
framework:
    messenger:
        transports:
            inbox:
                dsn: 'inbox://default?queue_name=inbox'
                serializer: 'Freyr\MessageBroker\Inbox\Serializer\TypedInboxSerializer'
                options:
                    auto_setup: true

        routing:
            # Messages will be routed by their PHP class name
            'App\Message\OrderPlaced': inbox
            'App\Message\OrderCancelled': inbox
            'App\Message\UserRegistered': inbox
            'App\Message\UserUpdated': inbox
