parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Freyr\MessageBroker\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Message/'
            - '../src/Kernel.php'

    Freyr\MessageBroker\Command\SendMessages:
        arguments:
            $bus: '@messenger.bus.default'
        tags: ['console.command']

    # simplified serializer
    messenger.transport.serializer: '@Freyr\MessageBroker\JsonSerializer'
